# use java support.
language: java
jdk:
  - oraclejdk8

# use operating systems
os:
  - linux
  - osx

# run in container und keep gradle cache.
sudo: false
cache:
  directories:
    - $HOME/.gradle

# run on xvfb screen.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# skip install stage.
install: true

# run gradle build.
env:
  - _JAVA_OPTIONS=
  - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k"

script:
  - ./gradlew build
