# use java support.
language: java
jdk:
  - oraclejdk8

# run in container und keep gradle cache.
sudo: false
cache:
  directories:
    - $HOME/.gradle

# run with xvfb and randr extension (resize and rotate).
before_install:
  - "export DISPLAY=:99.0"
  - "/usr/bin/Xvfb -extension RANDR :99 -ac -screen 0 1280x1024x16 &"

# run gradle build.
install: true
script: ./gradlew build
